import { Document } from "mongoose";
export interface INbaPlayerhModel extends Document {
    teamId: string,
    goalServeTeamId: number,
    goalServePlayerId: number,
    age: string,
    college: string,
    heigth: string,
    name: string,
    number: string,
    position: string,
    salary: string,
    weigth: string,
    isGamePlayer: Boolean,
    game : {
        assists_per_game: string,
        blocks_per_game: string,
        defensive_rebounds_per_game: string,
        efficiency_rating: string,
        fouls_per_game: string,
        games_played: string,
        games_started: string,
        minutes: string,
        offensive_rebounds_per_game: string,
        points_per_game: string,
        rank: string,
        rebounds_per_game: string,
        steals_per_game: string,
        turnovers_per_game: string,
    },
    isShootingPlayer : Boolean, 
    shooting : {
        fg_attempts_per_game: string,
        fg_made_per_game: string,
        fg_pct: string,
        field_goal_pct_avg: string,
        free_throws_attempts_per_game: string,
        free_throws_made_per_game: string,
        free_throws_pct: string,
        points_per_shot: string,
        rank: string,
        three_point_attempts_per_game: string,
        three_point_made_per_game: string,
        three_point_pct: string,
        two_point_attemps_per_game: string,
        two_point_made_per_game: string,
        two_point_pct: string,
    },
}