import { Document } from "mongoose";
export interface INbaPlayerhModel extends Document {
    teamId: String,
    goalServeTeamId: Number,
    goalServePlayerId: Number,
    age: String,
    college: String,
    heigth: String,
    name: String,
    number: String,
    position: String,
    salary: String,
    weigth: String,
    isGamePlayer: Boolean,
    game : {
        assists_per_game: String,
        blocks_per_game: String,
        defensive_rebounds_per_game: String,
        efficiency_rating: String,
        fouls_per_game: String,
        games_played: String,
        games_started: String,
        minutes: String,
        offensive_rebounds_per_game: String,
        points_per_game: String,
        rank: String,
        rebounds_per_game: String,
        steals_per_game: String,
        turnovers_per_game: String,
    },
    isShootingPlayer : Boolean, 
    shooting : {
        fg_attempts_per_game: String,
        fg_made_per_game: String,
        fg_pct: String,
        field_goal_pct_avg: String,
        free_throws_attempts_per_game: String,
        free_throws_made_per_game: String,
        free_throws_pct: String,
        points_per_shot: String,
        rank: String,
        three_point_attempts_per_game: String,
        three_point_made_per_game: String,
        three_point_pct: String,
        two_point_attemps_per_game: String,
        two_point_made_per_game: String,
        two_point_pct: String,
    },
}