import { Document } from "mongoose";

export interface INflPlayerModel extends Document {
  goalServeTeamId: String;
  goalServePlayerId: { type: Number };
  age: String;
  experience_years: String;
  college: String;
  height: String;
  name: String;
  number: String;
  positionName: String;
  position: String;
  salarycap: String;
  weight: String;
  isPassingPlayer: Boolean;
  passing?: {
    completion_pct: String;
    completions: String;
    interceptions: String;
    interceptions_pct: String;
    longest_pass: String;
    passing_attempts: String;
    passing_touchdowns: String;
    passing_touchdowns_pct: String;
    quaterback_rating: String;
    rank: String;
    sacked_yards_lost: String;
    sacks: String;
    yards: String;
    yards_per_game: String;
    yards_per_pass_avg: String;
  };

  isRushingPlayer: Boolean;
  rushing?: {
    fumbles: String;
    fumbles_lost: String;
    longest_rush: String;
    over_20_yards: String;
    rank: String;
    rushing_attempts: String;
    rushing_first_downs: String;
    rushing_touchdowns: String;
    yards: String;
    yards_per_game: String;
    yards_per_rush_avg: String;
  };
  isReceivingPlayer: Boolean;
  receiving?: {
    fumbles: String;
    fumbles_lost: String;
    longest_reception: String;
    over_20_yards: String;
    rank: String;
    receiving_first_downs: String;
    receiving_targets: String;
    receiving_touchdowns: String;
    receiving_yards: String;
    receptions: String;
    yards_after_catch: String;
    yards_per_game: String;
    yards_per_reception_avg: String;
  };
  isDefensePlayer: Boolean;
  defence?: {
    assisted_tackles: String;
    blocked_kicks: String;
    forced_fumbles: String;
    fumbles_recovered: String;
    fumbles_returned_for_touchdowns: String;
    intercepted_returned_yards: String;
    interceptions: String;
    interceptions_returned_for_touchdowns: String;
    longest_interception_return: String;
    passes_defended: String;
    rank: String;
    sacks: String;
    tackles_for_loss: String;
    total_tackles: String;
    unassisted_tackles: String;
    yards_lost_on_sack: String;
  };
  isScoringPlayer: Boolean;
  scoring?: {
    extra_points: String;
    field_goals: String;
    name: String;
    rank: String;
    receiving_touchdowns: String;
    return_touchdowns: String;
    rushing_touchdowns: String;
    total_points: String;
    total_points_per_game: String;
    total_touchdowns: String;
    two_point_conversions: String;
  };
  isReturningPlayer: Boolean;
  returning?: {
    fair_catches: String;
    kickoff_return_touchdows: String;
    kickoff_return_yards: String;
    kickoff_returned_attempts: String;
    longes_kickoff_return: String;
    longest_punt_return: String;
    punt_return_touchdowns: String;
    punts_returned: String;
    rank: String;
    yards_per_kickoff_avg: String;
    yards_per_punt_avg: String;
    yards_returned_on_punts: String;
  };
  isKickingPlayer: Boolean;
  kicking?: {
    extra_points_attempts: String;
    extra_points_made: String;
    extra_points_made_pct: String;
    field_goals_attempts: String;
    field_goals_from_1_19_yards: String;
    field_goals_from_20_29_yards: String;
    field_goals_from_30_39_yards: String;
    field_goals_from_40_49_yards: String;
    field_goals_from_50_yards: String;
    field_goals_made: String;
    field_goals_made_pct: String;
    longest_goal_made: String;
    rank: String;
  };
  isPuntingPlayer: Boolean;
  punting?: {
    blocked_punts: String;
    fair_catches: String;
    gross_punt_yards: String;
    gross_punting_avg: String;
    inside_20_yards_punt: String;
    longest_punt: String;
    net_punting_avg: String;
    punts: String;
    punts_returned: String;
    rank: String;
    touchbacks: String;
    yards_returned_on_punts: String;
    yards_returned_on_punts_avg: String;
  };
}
