import { Document } from "mongoose";
export interface INhlPlayerhModel extends Document {
    teamId: String,
    goalServeTeamId: Number,
    goalServePlayerId: Number,
    assists: String,
    faceoffs_lost: String,
    faceoffs_pct: String,
    faceoffs_won: String,
    game_winning_goals: String,
    games_played: String,
    goals: String,
    name: String,
    penalty_minutes: String,
    plus_minus: String,
    points: String,
    pos: String,
    production_time: String,
    rank: String,
    shifts: String,
    shootout_attempts: String,
    shootout_goals: String,
    shootout_pct: String,
    isGoalKeeper: Boolean,
    age: String,
    birth_place: String,
    height: String,
    number: String,
    salarycap: String,
    shot: String,
    weight: String,
    position: String,
}